### ISSUE TITLE
Doublecap :: Delete ghost outside of cap event

### ISSUE THREAD

**Issue by Dennogin** [softashell/nt-sourcemod-plugins#18]
The ghost gets deleted when captured, which will prevent a standard double cap. But if the ghost is close to a friendly capzone and the round ends whether through a timeout or round win, a player can still grab the ghost and bring it to the friendly capzone and still attempt a double cap.
Simply put, adding a function that checks to see if the round has ended and triggering the RemoveGhost function when the round has ended (or if a round is no longer active) would prevent a ghost on the ground or in someone's inventory the potential of triggering a double cap.

**Comment by Rainyan** [comment]
This should be fixed now.

**Comment by Rainyan** [comment]
Reopening as per 2984d934ad243324eec8eb0126c54a7a68bac149, #20

**Comment by Rainyan** [comment]
@Dennogin Could you try if the doublecap plugin in this version is working correctly: https://github.com/Rainyan/nt-sourcemod-plugins/archive/refs/heads/bug/doublecap.zip

**Comment by Dennogin** [comment]
Compiling and uploading now, people on right now so I'll tell you how it goes in a bit

**Comment by Dennogin** [comment]
So far it looks like its working fine, it disappears after round end when on the ground, just waiting to test if it disappears in inventory on round end as well

**Comment by Dennogin** [comment]
Speak of the devil, also disappeared from inventory on round end, everything looks stable, nice work :)

**Comment by Rainyan** [comment]
Ok thanks, I'm closing this as completed then, hopefully for good this time
