### ISSUE TITLE
No ghost on new round

### ISSUE THREAD

**Issue by NotHosomi** [softashell/nt-sourcemod-plugins#20]
Sometimes there is no ghost when a new round starts.
People have also reported seeing two ghost ui icons, and the second icon disappears when the ghost gets picked up.
Probably caused by the recent pr to the doublecap plugin

**Comment by Dennogin** [comment]
Can confirm when I moved the plugin to Disabled the ghost spawned normally

**Comment by Rainyan** [comment]
Thanks for reporting. I've reverted the change and reopening #18
