### ISSUE TITLE
Weapon duplication bug in nt_drop plugin

### ISSUE THREAD

**Issue by bauxiteDYS** [softashell/nt-sourcemod-plugins#28]
I think the bug is something to do with the code on line 336:

`SetEntData(weapon, spawnflags, GetEntData(weapon, spawnflags) & ~SF_NORESPAWN);`

It seems that if not changing the spawn flags the weapons can't easily be duped, but otherwise it's simple to dupe them by rapidly spamming toss/use/slot 1 keys.

Although might need a bit more investigation.

**Comment by Rainyan** [comment]
Reopen as per 81c242d1eea1d5d411abeddba1d2b9e0a3e3b3e8
